server:
  port: 80

spring:
  application:
    name: ace-openfeign-consumer

  cloud:
    consul:
      discovery:
        prefer-ip-address: true #优先使用服务ip进行注册
        service-name: ${spring.application.name}
      host: localhost
      port: 8500
