version: '3.5'

networks:
  ace-net: # 网络名
    name: ace-cloud-network
    driver: bridge


services:
  consul_leader:
    image: consul:1.15.4
    container_name: consul-leader1111111
    restart: always
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - 8500:8500
    command:
      - agent --server=true --bootstrap-expect=3 -ui
    networks:
      - ace-cloud-network
