version: '3.8'


networks:
  ace-network: # 网络名
    name: ace-network
    driver: bridge



services:
  mysql-8:
    image: mysql:latest
    container_name: mysql-8
    restart: always
    environment:
      MYSQL_DATABASE: ace
      MYSQL_USER: garlam
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - ace-network

  redis:
    image: redis:latest
    container_name: redis-7
    restart: always
    ports:
      - 6379:6379
    networks:
      - ace-network

  consul-1:
    image: consul:1.15.4
    container_name: consul-1
    restart: always
    ports:
      - 8501:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command: >
      agent --server=true
      --bootstrap-expect=3
      --client=0.0.0.0
      --ui
    networks:
      - ace-network

  consul-2:
    image: consul:1.15.4
    container_name: consul-2
    restart: always
    ports:
      - 8502:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command: >
      agent --server=true
      --bootstrap-expect=3
      --client=0.0.0.0
      --join consul-1
      --ui
    networks:
      - ace-network


  consul-3:
    image: consul:1.15.4
    container_name: consul-3
    restart: always
    ports:
      - 8503:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command: >
      agent --server=true
      --bootstrap-expect=3
      --client=0.0.0.0
      --join consul-1
      --ui
    networks:
      - ace-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - ace-network

  ace-gateway:
    build:
      context: ./ace-gateway
      dockerfile: Dockerfile
    container_name: ace-gateway
    restart: always
    ports:
      - 9500:9500
    depends_on:
      - zipkin
      - consul-1
      - consul-2
      - consul-3
    networks:
      - ace-network


  ace-entities-module-1:
    build:
      context: ./ace-entities-module
      dockerfile: Dockerfile
    container_name: ace-entities-module-1
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - redis
      - mysql-8
      - zipkin
      - consul-1
      - consul-2
      - consul-3
      - ace-gateway
    networks:
      - ace-network




  ace-entities-module-2:
    build:
      context: ./ace-entities-module
      dockerfile: Dockerfile
    container_name: ace-entities-module-2
    restart: always
    ports:
      - 8002:8000
    depends_on:
      - redis
      - mysql-8
      - zipkin
      - consul-1
      - consul-2
      - consul-3
      - ace-gateway
    networks:
      - ace-network

  ace-entities-module-3:
    build:
      context: ./ace-entities-module
      dockerfile: Dockerfile
    container_name: ace-entities-module-3
    restart: always
    ports:
      - 8003:8000
    depends_on:
      - redis
      - mysql-8
      - zipkin
      - consul-1
      - consul-2
      - consul-3
      - ace-gateway
    networks:
      - ace-network

  ace-client:
    build:
      context: ./ace-client
      dockerfile: Dockerfile
    container_name: ace-client
    restart: always
    ports:
      - 80:8090
    depends_on:
      - redis
      - zipkin
      - consul-1
      - consul-2
      - consul-3
    networks:
      - ace-network
