#docker compose -f /Users/garlam/IdeaProjects/ace-cloud/Docker-compose.yml -p ace-cloud up -d
version: '3.8'


networks:
  ace-network: # 网络名
    name: ace-network
    driver: bridge




services:
  consul-leader:
    image: consul:1.15.4
    container_name: consul-leader
    restart: always
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command: >
      agent 
      --server=true
      --bootstrap-expect=3
      --client=0.0.0.0
      --ui
      --node=consul-leader
    networks:
      - ace-network
    #  --advertise=192.168.1.2 绑定ip

  consul-1:
    image: consul:1.15.4
    container_name: consul-1
    restart: always
    ports:
      - 8501:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command: >
      agent 
      --server=true
      --bootstrap-expect=3
      --client=0.0.0.0
      --join consul-leader
      --ui
      --node=consul-1
    depends_on:
      - consul-leader
    networks:
      - ace-network

  consul-2:
    image: consul:1.15.4
    container_name: consul-2
    restart: always
    ports:
      - 8502:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command: >
      agent 
      --server=true
      --bootstrap-expect=3
      --client=0.0.0.0
      --join consul-leader
      --ui
      --node=consul-2
    depends_on:
      - consul-1
    networks:
      - ace-network

  mysql8:
    image: mysql:latest
    container_name: mysql8
    restart: always
    environment:
      MYSQL_DATABASE: ace
      MYSQL_USER: garlam
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    depends_on:
      - consul-leader
      - consul-1
      - consul-2
    networks:
      - ace-network

  redis:
    image: redis:latest
    container_name: redis-7
    restart: always
    ports:
      - 6379:6379
    depends_on:
      - consul-leader
      - consul-1
      - consul-2
    networks:
      - ace-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - ace-network

  ace-gateway:
    build:
      context: ./ace-gateway
      dockerfile: Dockerfile
    container_name: ace-gateway
    #   restart: always
    ports:
      - 9500:9500
    depends_on:
      - zipkin
      - consul-leader
      - consul-1
      - consul-2
    networks:
      - ace-network

  ace-client:
    build:
      context: ./ace-client
      dockerfile: Dockerfile
    container_name: ace-client
    # restart: always
    ports:
      - 8090:8090
    depends_on:
      - consul-leader
      - consul-1
      - consul-2
      - redis
      - zipkin
    networks:
      - ace-network


#  ace-client-2:
#    build:
#      context: ./ace-client
#      dockerfile: Dockerfile
#    container_name: ace-client-2
#    # restart: always
#    ports:
#      - 8092:8090
#    depends_on:
#      - consul-leader
#      - consul-1
#      - consul-2
#      - redis
#      - zipkin
#    networks:
#      - ace-network



  ace-entities-module-1:
    build:
      context: ./ace-entities-module
      dockerfile: Dockerfile
    container_name: ace-entities-module-1
    # restart: always
    environment:
      - SERVICE_NAME=ace-entities-module-1
      - SERVICE_PORT=8000
    ports:
      - 8001:8000
    depends_on:
      - consul-leader
      - consul-1
      - consul-2
      - redis
      - mysql8
      - zipkin
      - ace-gateway
    networks:
      - ace-network

  ace-entities-module-2:
    build:
      context: ./ace-entities-module
      dockerfile: Dockerfile
    container_name: ace-entities-module-2
    #  restart: always
    environment:
      - SERVICE_NAME=ace-entities-module-2
      - SERVICE_PORT=8000
    ports:
      - 8002:8000
    depends_on:
      - consul-leader
      - consul-1
      - consul-2
      - redis
      - mysql8
      - zipkin
      - ace-gateway
    networks:
      - ace-network

  ace-entities-module-3:
    build:
      context: ./ace-entities-module
      dockerfile: Dockerfile
    container_name: ace-entities-module-3
    #  restart: always
    environment:
      - SERVICE_NAME=ace-entities-module-3
      - SERVICE_PORT=8000
    ports:
      - 8003:8000
    depends_on:
      - consul-leader
      - consul-1
      - consul-2
      - redis
      - mysql8
      - zipkin
      - ace-gateway
    networks:
      - ace-network


